config/routes.rb
Rails.application.routes.draw do
  root "questions#index"
  resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :answers, only: [:index, :create]

  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :question_id, presence: true
  validates :answer, length: { minimum: 50 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, length: { minimum: 40 }
  validates :description, length: { minimum: 150 }
end

app/controllers/answers_controller.rb
require 'pry'
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def create
    @question = Question.find(params[:question_id])
    @answers = @question.answers
    @answer = Answer.new(answer_params)
    @answer.question = @question
    if @answer.save
      flash.notice = "Answer saved successfully!"
      redirect_to question_path(@question)
    else
      flash.notice = @answer.errors.full_messages.join(", ")
      render 'questions/show'
    end
  end

  private
  def answer_params
    params.require(:answer).permit(
    :question_id,
    :answer
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash.notice = "Question created!"
      redirect_to questions_path
    else
      flash.notice = "Question not created"

      render "new"
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash.notice = "Question updated!"
      redirect_to question_path
    else
      @message = "Question not updated"
      render "edit"
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.answers.destroy
    @question.destroy

    redirect_to questions_path
  end

  def question_params
    params.require(:question).permit(
    :title,
    :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer, size: "50x5" %>
  </p>

  <p>
    <%= f.submit "Submit Answer" %>
  </p>
<% end %>

app/views/answers/new.html.erb
<h2>Submit a new answer for <%= @question.title %></h2>

<%= form_for([@question, @answer]) do |f| %>
  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer, size: "50x5" %>
  </p>

  <p>
    <%= f.submit "Submit Answer" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |k,v| %>
    <h2><%= v %></h2>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit question</h2>

<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "50x5" %>
  </p>

  <p>
    <%= f.submit "Submit Changes" %>
  </p>
<% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %></li>
  <% end %>
</ul>

<%= link_to "Submit a new question", new_question_path %>

app/views/questions/new.html.erb
<h2>Submit a new question</h2>

<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "50x5" %>
  </p>

  <p>
    <%= f.submit "Submit Question" %>
  </p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p> <%= @question.description %> </p>

<h3><%= @answers.empty? ? "No answers submitted for this question" : "Answers"%></h3>
<ul>
  <% @answers.each do |answer| %>
  <li><%= answer.answer %></li>
  <% end %>
</ul>

<h2>Submit a new answer for <%= @question.title %></h2>

<%= render 'answers/form' %>

<%= link_to "Edit Question", edit_question_path(@question) %>
<%= link_to "All Questions", questions_path %>
<%= link_to "DESTROY!!!! MUAHAHA", question_path(@question), method: :delete %>